Module8 task3
htmlacademy-yii/248841-task-force-1 pull request #19
Opened 2021-10-03 17:45 UTC by Lobochkin

2021-10-04 18:22 UTC, andrewverner requested changes

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/controllers/AccountController.php
> +                    return 'Ошибка сохранения файлов!';
Exception

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/controllers/MyTasksController.php
> +            case 'delay':
const

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/models/Account.php
> +        $userId = \Yii::$app->user->identity->getId();
$this->user->id

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/models/Account.php
> +            $user = Users::findOne($userId);
$this->user

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/models/Account.php
> +        if ($_FILES['Account']['tmp_name']['avatarUrl'] || $_FILES['avatarUrl']['tmp_name']) {
if ($avatarUrl = UploadedFile::getInstanceByName('Account[avatarUrl]')) {...

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/models/Account.php
> +            $avatarUrl = UploadedFile::getInstanceByName('Account[avatarUrl]');
drop

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/models/Account.php
> +        if ($_FILES['files']) {
if ($files = UploadedFile::getInstancesByName('files')) {...

2021-10-04 18:22 UTC, denis-khodakovskiy commented on frontend/models/Account.php
> +            $photos = PhotoWork::find()->where(['user_id' => $userId])->all();
$this->user->photoWork

2021-10-04 18:22 UTC, andrewverner commented on frontend/models/Account.php
> +        $newCategory = !$this->category ? [] : $this->category;
$fromDB = $this->user->userCategory;
        $fromRequest = $this->category;

        $toActivateOrAdd = array_diff($fromRequest, $fromDB);
        $toDeactivate = array_diff($fromDB, $fromRequest);

        foreach ($toDeactivate as $categoryId) {
            //..
        }

        foreach ($toActivateOrAdd as $categoryId) {
            $affectedRowsCount = UserCategory::updateAll([
                'active' => 'Y',
            ], [
                'user_id' => $this->user->id,
                'category_id' => $categoryId,
            ]);

            if (!$affectedRowsCount) {
                $model = new UserCategory();
                $model->user_id = $this->user->id;
                $model->category_id = $categoryId;
                $model->active = 'Y';
                $model->save();
            }
        }

2021-10-04 18:22 UTC, andrewverner commented on frontend/models/Account.php
> +        $this->user->phone = substr($this->phone,0,12);
drop,
preg_replace ^\d

2021-10-04 18:22 UTC, andrewverner commented on frontend/models/Account.php
> +            $this->user->not_show_profile = 'Y';
`$this->user->not_show_profile = $this->notShowProfile === 1 ? 'Y' : 'N';`

2021-10-05 17:28 UTC, Lobochkin commented on frontend/controllers/MyTasksController.php
> +            case 'delay':
сделал

2021-10-05 17:28 UTC, Lobochkin commented on frontend/models/Account.php
> +        $userId = \Yii::$app->user->identity->getId();
сделал

2021-10-05 17:30 UTC, Lobochkin commented on frontend/models/Account.php
> +            $user = Users::findOne($userId);
сделал

2021-10-05 17:31 UTC, Lobochkin commented on frontend/models/Account.php
> +        if ($_FILES['Account']['tmp_name']['avatarUrl'] || $_FILES['avatarUrl']['tmp_name']) {
сделал

2021-10-05 17:32 UTC, Lobochkin commented on frontend/models/Account.php
> +        if ($_FILES['files']) {
сделал

2021-10-05 17:45 UTC, Lobochkin commented on frontend/models/Account.php
> +            $photos = PhotoWork::find()->where(['user_id' => $userId])->all();
сделал

2021-10-05 17:52 UTC, Lobochkin commented on frontend/models/Account.php
> +        $this->user->phone = substr($this->phone,0,12);
сделал

2021-10-05 17:55 UTC, Lobochkin commented on frontend/models/Account.php
> +            $this->user->not_show_profile = 'Y';
сделал

2021-10-05 18:40 UTC, Lobochkin commented on frontend/models/Account.php
> +        $newCategory = !$this->category ? [] : $this->category;
сделал

2021-10-05 20:04 UTC, Lobochkin commented on frontend/controllers/AccountController.php
> +                    return 'Ошибка сохранения файлов!';
сделал

2021-10-07 08:30 UTC, merged