Создал класс для обработки заданий
htmlacademy-yii/248841-task-force-1 pull request #2
Opened 2020-11-24 09:46 UTC by Lobochkin

2020-11-25 07:07 UTC, nikserg requested changes
Нужно доработать некоторые моменты.

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +use http\QueryString;
Лишний use?

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +class Task
Неплохо дать классу небольшой комментарий.

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +    protected $arMapActionAndStatus = [
Префикс "ar" означает "array"? Такие префиксы типа переменной не приняты в конвенции camelCase в PHP, лучше их не использовать. 
Кроме того, "MapActionAndStatus" не очень удачное описание происходящего. Массив хранит человекопонятные имена действий или статусов, поэтому логично его назвать как-нибудь типа statusNames.
Ты смешиваешь в одном массиве действия и статусы. А что, если у них будет одинаковое название? Уже сейчас виден костыль, который тебе пришлось применить: ACTION_CANCEL имеет значение cancel_task, хотя напрашивается просто cancel. Лучше разделить, сделать массив statusNames и actionNames.

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +            'implementer' => self::ACTION_DECLINE,
implementer - это роль? Тогда нужна константа ROLE_IMPLEMENTER.

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +    public function __construct(int $intIdTask,int $intIdStatus)
Немного плывет форматирование, нет пробела после запятой, ну и по всему коду по мелочи такое. Если используешь IDE PhpStorm, там есть автоформатирование, комбинация клавиш Ctrl+Alt+L (или Shift+Alt+L, не помню точно). Советую воспользоваться, очень удобно.

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +        if(strlen($action) < 1){
Условие можно сократить до if (!$action)

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +        if(strlen($action) < 1){
Аналогично в других местах

2020-11-25 07:07 UTC, nikserg commented on Task.php
> +    public $strUser = ''; // Исполнитель или Заказчик implementer|customer
Не очень понятен смысл этой переменной.

2020-11-25 08:02 UTC, Lobochkin commented on Task.php
> +use http\QueryString;
Да, не знаю откуда вылез, создавал класс с помощью phpstorm, может он подставил

2020-11-25 08:04 UTC, Lobochkin commented on Task.php
> +    public $strUser = ''; // Исполнитель или Заказчик implementer|customer
Туда записываю роль пользователя, что бы потом с помощью метода getNextAction() получить нужные кнопки для отображения

2020-11-25 11:08 UTC, Lobochkin commented on Task.php
> +    protected $arMapActionAndStatus = [
Не совсем понял , если я разобью массив MapActionAndStatus на два отдельных statusNames и actionNames, то по сути ничего не измениться , значение константы ACTION_CANCEL и сейчас можно изменить на cancel

2020-11-25 11:10 UTC, Lobochkin commented on Task.php
> +class Task
хорошо

2020-11-27 07:16 UTC, nikserg commented on Task.php
> +    protected $arMapActionAndStatus = [
Сейчас нельзя, так как получится два одинаковых ключа массива.

2020-11-27 07:17 UTC, nikserg commented on Task.php
> +            'implementer' => self::ACTION_DECLINE,
Это сделал?

2020-11-27 07:17 UTC, nikserg commented on Task.php
> +    public function __construct(int $intIdTask,int $intIdStatus)
?

2020-11-27 07:17 UTC, nikserg commented on Task.php
> +        if(strlen($action) < 1){
?

2020-11-27 07:17 UTC, nikserg commented on Task.php
> +    public $strUser = ''; // Исполнитель или Заказчик implementer|customer
По идее, в getNextAction

2020-11-27 08:07 UTC, Lobochkin commented on Task.php
> +    protected $arMapActionAndStatus = [
+

2020-11-27 08:07 UTC, Lobochkin commented on Task.php
> +            'implementer' => self::ACTION_DECLINE,
+

2020-11-27 08:08 UTC, Lobochkin commented on Task.php
> +        if(strlen($action) < 1){
+

2020-11-27 08:08 UTC, Lobochkin commented on Task.php
> +    public $strUser = ''; // Исполнитель или Заказчик implementer|customer
+

2020-11-27 08:08 UTC, Lobochkin commented on Task.php
> +    public function __construct(int $intIdTask,int $intIdStatus)
сделал

2020-11-27 08:14 UTC, merged